### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by StefanS-O** [StefanS-O/jupiterbroadcasting-hugo-mvp#13]
figure out a good way to integrate search. Clientside like Lunr.js will probably not perform due to index size.

**Comment by theZMC** [comment]
Since golang seems to be a theme here (which it should be), maybe [zinc](https://github.com/zinclabs/zinc) would fit the bill?

**Comment by StefanS-O** [comment]
Thanks @theZMC that looks super interesting. I love ElasticSearch, i just hate managing the stack. Will check it out.
