### ISSUE TITLE
Needs Docker build functionality

### ISSUE THREAD

**Issue by theZMC** [StefanS-O/jupiterbroadcasting-hugo-mvp#27]
Since the README makes mention of a TBD for Docker, I went ahead and created a basic `Dockerfile` and `docker-compose.yml` that will enable building the static site and copying it over to an `nginx` container for deployment. This will need to be refined over time once the final decision about container registry is determined.

My PR:
https://github.com/StefanS-O/jupiterbroadcasting-hugo-mvp/pull/26

**Comment by StefanS-O** [comment]
Nice, thanks! I wrote TBD because i was unsure if we need a docker image, when Hugo is just a binary install. But having the Docker Image makes adding nodejs stuff way easier.
